In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# symmetric matrix
Q = np.random.rand(5,5)
A = (Q.T + Q)/2
print(A)

[[0.04527035 0.6439847  0.20962324 0.74872545 0.46749235]
 [0.6439847  0.27437841 0.46439066 0.40756364 0.47695604]
 [0.20962324 0.46439066 0.40975483 0.3861069  0.6291217 ]
 [0.74872545 0.40756364 0.3861069  0.31388042 0.62000892]
 [0.46749235 0.47695604 0.6291217  0.62000892 0.08238706]]


In [5]:
eigenvalues, v = np.linalg.eig(A)
print(eigenvalues)

[ 2.2538427   0.20520994 -0.70219854 -0.52655713 -0.1046259 ]
